name: 'Lock down repository'

on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          issue-labels: 'off-topic'
          issue-comment: >
            Thanks for your contribution!
            
            However, this repository does not accept bug reports,
            since this is only a mirror of
            https://gitlab.com/1O/bitwarden_rs-backup.

            Please feel free to open the issue there.
          skip-closed-issue-comment: true
          pr-comment: >
            Thanks for your contribution!
          
            However, this repository does not accept pull requests,
            since this is only a mirror of
            https://gitlab.com/1O/bitwarden_rs-backup.

            Please feel free to open the pull request there.
          skip-closed-pr-comment: true